apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  clusterName: hello-config-sync
  git:
    syncRepo: https://github.com/sidgs/hello-config-sync
    secretType: none
    policyDir: policy
