
# root-sync.yaml
apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: bookinfo-configsync
  namespace: config-management-system
spec:
  sourceType: git
  # sourceFormat: ROOT_FORMAT
  git:
    repo: https://github.com/sidgs/hello-config-sync
    # revision: ROOT_REVISION
    branch: master
    dir: bookinfo
    auth: none
    # gcpServiceAccountEmail: ROOT_EMAIL
    # secretRef:
    # name: ROOT_SECRET_NAME
    # noSSLVerify: ROOT_NO_SSL_VERIFY
    # caCertSecretRef:
    # name: ROOT_CA_CERT_SECRET_NAME